name: pit_coverage
on:
  push:
    branches:
      - master
      - isw2-testing-dev
      - isw2-testing
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'


      - name: launch-pit
        run: mvn clean verify -P mutation-cov
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: pit-report
          path: tajo-cluster-tests/target/pit-reports/
          if-no-files-found: error
